# Generated by Django 2.1.4 on 2019-01-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateField(auto_now=True)),
                ('body', models.CharField(max_length=1000)),
                ('image', models.ImageField(height_field=200, upload_to='imgs/')),
            ],
        ),
    ]
